using System.Collections.Generic;

public static class SkillRepository
{
  public static List<ISkillEntity> entities = new List<ISkillEntity>() 
  {
    new SkillEntity() {
      Id                   = SkillId.NormalBullet1,
      Name                 = "通常弾",
      MaxExp               = 999,
      FirstRecastTime      = 2f,
      LastRecastTime       = 1f,
      FirstPower           = 5,
      LastPower            = 20,
      FirstPenetrableCount = 1,
      LastPenetrableCount  = 2,
      SpeedGrowthRate      = 2f,
      Attr                 = (uint)(Attribute.Non),
      Prefab               = "Bullet/NormalBullet1/Object.prefab",
      GrowthType           = Growth.Fast,
      Impact               = 1f,
      IconNo               = 0,
      Aiming               = SkillAimingType.Nearest,
    },
    
    new SkillEntity() {
      Id                   = SkillId.NormalBullet2,
      Name                 = "通常弾+",
      MaxExp               = 9999,
      FirstRecastTime      = 2f,
      LastRecastTime       = 1f,
      FirstPower           = 50,
      LastPower            = 100,
      FirstPenetrableCount = 0,
      LastPenetrableCount  = 0,
      SpeedGrowthRate      = 1f,
      Attr                 = (uint)(Attribute.Non),
      Prefab               = "Bullet/NormalBullet2/Object.prefab",
      GrowthType           = Growth.Normal,
      Impact               = 5f,
      IconNo               = 1,
      Aiming               = SkillAimingType.Nearest,
    },
    
    new SkillEntity() {
      Id                   = SkillId.PiercingBullet1,
      Name                 = "フェザーショット",
      MaxExp               = 9999,
      FirstRecastTime      = 5f,
      LastRecastTime       = 3f,
      FirstPower           = 10,
      LastPower            = 30,
      FirstPenetrableCount = 0,
      LastPenetrableCount  = 0,
      SpeedGrowthRate      = 1f,
      Attr                 = (uint)(Attribute.Non),
      Prefab               = "Bullet/PiercingBullet1/Object.prefab",
      GrowthType           = Growth.Fast,
      Impact               = 0.5f,
      IconNo               = 6,
      Aiming               = SkillAimingType.Nearest,
    },
    
    new SkillEntity() {
      Id                   = SkillId.FireBullet1,
      Name                 = "ファイアバレット",
      MaxExp               = 2000,
      FirstRecastTime      = 2f,
      LastRecastTime       = 1f,
      FirstPower           = 10,
      LastPower            = 30,
      FirstPenetrableCount = 0,
      LastPenetrableCount  = 0,
      SpeedGrowthRate      = 1f,
      Attr                 = (uint)(Attribute.Fir),
      Prefab               = "Bullet/FireBullet1/Object.prefab",
      GrowthType           = Growth.Normal,
      Impact               = 1f,
      IconNo               = 3,
      Aiming               = SkillAimingType.Weakest,
    },
    
    new SkillEntity() {
      Id                   = SkillId.WaterBullet1,
      Name                 = "ウォーターボール",
      MaxExp               = 2000,
      FirstRecastTime      = 1f,
      LastRecastTime       = 0.2f,
      FirstPower           = 10,
      LastPower            = 30,
      FirstPenetrableCount = 0,
      LastPenetrableCount  = 0,
      SpeedGrowthRate      = 1f,
      Attr                 = (uint)(Attribute.Wat),
      Prefab               = "Bullet/WaterBullet1/Object.prefab",
      GrowthType           = Growth.Normal,
      Impact               = 1f,
      IconNo               = 4,
      Aiming               = SkillAimingType.Weakest,
    },
    
    new SkillEntity() {
      Id                   = SkillId.ThunderBullet1,
      Name                 = "サンダーウェイブ",
      MaxExp               = 999,
      FirstRecastTime      = 1f,
      LastRecastTime       = 0.2f,
      FirstPower           = 2,
      LastPower            = 10,
      FirstPenetrableCount = 0,
      LastPenetrableCount  = 0,
      SpeedGrowthRate      = 1f,
      Attr                 = (uint)(Attribute.Thu),
      Prefab               = "Bullet/ThunderBullet1/Object.prefab",
      GrowthType           = Growth.Normal,
      Impact               = 3f,
      IconNo               = 5,
      Aiming               = SkillAimingType.Weakest,
    },
    
    new SkillEntity() {
      Id                   = SkillId.LeafBullet1,
      Name                 = "リーフカッター",
      MaxExp               = 999,
      FirstRecastTime      = 10f,
      LastRecastTime       = 5f,
      FirstPower           = 1,
      LastPower            = 5,
      FirstPenetrableCount = 0,
      LastPenetrableCount  = 0,
      SpeedGrowthRate      = 1f,
      Attr                 = (uint)(Attribute.Lef),
      Prefab               = "Bullet/LeafBullet1/Object.prefab",
      GrowthType           = Growth.Normal,
      Impact               = 10f,
      IconNo               = 2,
      Aiming               = SkillAimingType.Player,
    },
    
    new SkillEntity() {
      Id                   = SkillId.IceBullet1,
      Name                 = "アイスランス",
      MaxExp               = 999,
      FirstRecastTime      = 1f,
      LastRecastTime       = 0.2f,
      FirstPower           = 1,
      LastPower            = 10,
      FirstPenetrableCount = 0,
      LastPenetrableCount  = 0,
      SpeedGrowthRate      = 1f,
      Attr                 = (uint)(Attribute.Ice),
      Prefab               = "Bullet/IceBullet1/Object.prefab",
      GrowthType           = Growth.Normal,
      Impact               = 1f,
      IconNo               = 8,
      Aiming               = SkillAimingType.Weakest,
    },
    
    new SkillEntity() {
      Id                   = SkillId.WindBullet1,
      Name                 = "つむじ風",
      MaxExp               = 2000,
      FirstRecastTime      = 5f,
      LastRecastTime       = 2f,
      FirstPower           = 3,
      LastPower            = 10,
      FirstPenetrableCount = 0,
      LastPenetrableCount  = 0,
      SpeedGrowthRate      = 1f,
      Attr                 = (uint)(Attribute.Win),
      Prefab               = "Bullet/WindBullet1/Object.prefab",
      GrowthType           = Growth.Normal,
      Impact               = 10f,
      IconNo               = 7,
      Aiming               = SkillAimingType.Weakest,
    },
    
  };
}